upgrade to webrtc m120-6099。
versatica/libmediasoupclient pull request #179
Opened 2024-06-08 09:27 UTC by janreyho

I've upgraded `libmediasoupclient` to WebRTC m120-6099 and also updated the corresponding test demo, `mediasoup-broadcaster-demo`, to the same version. 

This upgrade allows for successful room entry and video stream publishing. 

Testing on a Mac with an M3 Max chip has been successful.

2024-06-12 09:20 UTC, jmillan commented
Hi @janreyho, 

The PR looks good, but the tests are still failing as in [PR](https://github.com/versatica/libmediasoupclient/tree/m120), which is what is blocking us from merging.

Would you please take a look at it so we make the test pass?

2024-06-12 12:24 UTC, janreyho commented
`python scripts/clang-tidy.py
/Users/hejiayi/Desktop/8_haoxinyun/gitlab/hxSDK/mediasoup/libmediasoupclient/.clang-tidy:5:1: error: unknown key 'AnalyzeTemporaryDtors'
AnalyzeTemporaryDtors: false
^~~~~~~~~~~~~~~~~~~~~
Error parsing /Users/hejiayi/Desktop/8_haoxinyun/gitlab/hxSDK/mediasoup/libmediasoupclient/.clang-tidy: Invalid argument
Enabled checks:
...
^~~~~~~~~~~~~~~~~~~~~
Error parsing /Users/hejiayi/Desktop/8_haoxinyun/gitlab/hxSDK/mediasoup/libmediasoupclient/.clang-tidy: Invalid argument
/Users/hejiayi/Desktop/8_haoxinyun/gitlab/hxSDK/mediasoup/libmediasoupclient/.clang-tidy:5:1: error: unknown key 'AnalyzeTemporaryDtors'
AnalyzeTemporaryDtors: false
^~~~~~~~~~~~~~~~~~~~~
Error parsing /Users/hejiayi/Desktop/8_haoxinyun/gitlab/hxSDK/mediasoup/libmediasoupclient/.clang-tidy: Invalid argument

clang-tidy -header-filter=^/Users/hejiayi/Desktop/8_haoxinyun/gitlab/hxSDK/mediasoup/libmediasoupclient/.* -p=/Users/hejiayi/Desktop/8_haoxinyun/gitlab/hxSDK/mediasoup/libmediasoupclient /Users/hejiayi/Desktop/8_haoxinyun/gitlab/hxSDK/mediasoup/libmediasoupclient/src/DataConsumer.cpp

/Users/hejiayi/Desktop/8_haoxinyun/gitlab/hxSDK/mediasoup/libmediasoupclient/.clang-tidy:5:1: error: unknown key 'AnalyzeTemporaryDtors'
AnalyzeTemporaryDtors: false
`

python scripts/clang-tidy.py generates many above errors

I use [libmediasoupclient](https://github.com/janreyho/libmediasoupclient) in [mediasoup-broadcaster-demo](https://github.com/janreyho/mediasoup-broadcaster-demo) is OK, and  joining a room and publishing a stream is successfully。

2024-06-12 13:21 UTC, jmillan commented
@janreyho, as I commented in your PR the current problem is that `libmediasoupclient` tests are failing, so very likely is the tests that need changes.

2024-06-12 14:41 UTC, janreyho commented
```
sh scripts/test.sh
[INFO] compiling mediasoupclient and test_mediasoupclient: cmake --build build
[ 15%] Built target sdptransform
[ 76%] Built target mediasoupclient
[ 92%] Built target test_sdptransform
[100%] Built target sdptransform_readme_helper
[INFO] running tests: ./build/test/test_mediasoupclient.app/Contents/MacOS/test_mediasoupclient
scripts/test.sh: line 45: ./build/test/test_mediasoupclient.app/Contents/MacOS/test_mediasoupclient: No such file or directory
```

@jmillan how to generated test_mediasoupclient

2024-06-12 15:41 UTC, jmillan commented
In order to build the tests you need to set the `-DMEDIASOUPCLIENT_BUILD_TESTS:BOOLEAN=ON` flag.

```
cmake . -Bbuild \
  -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
  -DMEDIASOUPCLIENT_BUILD_TESTS:BOOLEAN=ON \
  -DMEDIASOUPCLIENT_LOG_TRACE:BOOLEAN=ON \
  -DMEDIASOUPCLIENT_LOG_DEV:BOOLEAN=ON \
  -DLIBWEBRTC_INCLUDE_PATH:PATH=${PATH_TO_LIBWEBRTC_SOURCES} \
  -DLIBWEBRTC_BINARY_PATH:PATH=${PATH_TO_LIBWEBRTC_BINARY} \
  -DCMAKE_CXX_FLAGS="-fvisibility=hidden" \
  -DCLANG_TIDY_FIX=ON

make -C build/
```

2024-06-16 14:20 UTC, janreyho commented
@jmillan After modifying the three test case files:
```
test/src/Handler.test.cpp
test/src/MediaStreamTrackFactory.cpp
test/src/mediasoupclient.test.cpp
```
The individual TEST_CASE tests have all passed:
```assembly
(base) ➜  libmediasoupclient git:(m120) ✗ ./build/test/test_mediasoupclient.app/Contents/MacOS/test_mediasoupclient mediasoupclient
Filters: mediasoupclient mediasoupclient
===============================================================================
All tests passed (189 assertions in 1 test case)

(base) ➜  libmediasoupclient git:(m120) ✗ ./build/test/test_mediasoupclient.app/Contents/MacOS/test_mediasoupclient Handler
Filters: Handler Handler
===============================================================================
All tests passed (4 assertions in 1 test case)

(base) ➜  libmediasoupclient git:(m120) ✗
(base) ➜  libmediasoupclient git:(m120) ./build/test/test_mediasoupclient.app/Contents/MacOS/test_mediasoupclient Device
Filters: Device Device
===============================================================================
All tests passed (15 assertions in 1 test case)

(base) ➜  libmediasoupclient git:(m120) ./build/test/test_mediasoupclient.app/Contents/MacOS/test_mediasoupclient PeerConnection
Filters: PeerConnection PeerConnection
===============================================================================
All tests passed (8 assertions in 1 test case)

(base) ➜  libmediasoupclient git:(m120) ./build/test/test_mediasoupclient.app/Contents/MacOS/test_mediasoupclient SendHandler
Filters: SendHandler SendHandler
===============================================================================
All tests passed (16 assertions in 1 test case)

(base) ➜  libmediasoupclient git:(m120)
```
Other test cases are also OK, but the overall test reports：segmentation fault
```assembly
(base) ➜  libmediasoupclient git:(m120) ./build/test/test_mediasoupclient.app/Contents/MacOS/test_mediasoupclient
===============================================================================
All tests passed (338 assertions in 15 test cases)

[1]    45251 segmentation fault  ./build/test/test_mediasoupclient.app/Contents/MacOS/test_mediasoupclient
(base) ➜  libmediasoupclient git:(m120)
```
I still don't know how to locate the problem。

2024-06-19 08:14 UTC, jmillan requested changes

2024-06-19 08:14 UTC, jmillan commented on test/include/MediaStreamTrackFactory.hpp
> +        static Singleton instance; // 唯一实例
Please, comments only in english.

2024-06-19 08:14 UTC, jmillan commented on test/include/MediaStreamTrackFactory.hpp
> +    // 防止拷贝和赋值
Same, please replace all comments to english.

2024-06-19 08:14 UTC, jmillan commented on test/include/MediaStreamTrackFactory.hpp
> +        std::cout << "Singleton created\n";
remove.

2024-06-19 08:14 UTC, jmillan commented on test/include/MediaStreamTrackFactory.hpp
> +        std::cout << "Singleton destroyed\n";
remove.

2024-06-19 08:14 UTC, jmillan commented on test/include/MediaStreamTrackFactory.hpp
> +	*/
```suggestion
	/**
	* MediaStreamTrack holds reference to the threads of the PeerConnectionFactory.
	* Use plain pointers in order to avoid threads being destructed before tracks.
	*/
```

2024-06-19 08:14 UTC, jmillan commented on test/src/Handler.test.cpp
> +	//   new mediasoupclient::PeerConnection(nullptr, &PeerConnectionOptions));
Just remove if not needed.

2024-06-19 08:14 UTC, jmillan commented on test/src/MediaStreamTrackFactory.cpp
> +#define SINGLETON_H
`MEDIA_STREAM_TRACK_FACTORY`

2024-06-19 08:14 UTC, jmillan commented on test/src/MediaStreamTrackFactory.cpp
> +	void Singleton::createFactory()
```suggestion
	void MediaStreamTrackFactory::create()
```

2024-06-19 08:14 UTC, jmillan commented on test/src/MediaStreamTrackFactory.cpp
> +		// 调用 reset 函数以释放资源
englihs.

2024-06-19 08:14 UTC, jmillan commented on test/src/MediaStreamTrackFactory.cpp
> +			// Factory->Release();
remove code rather than comment.

2024-06-19 08:14 UTC, jmillan commented on test/src/MediaStreamTrackFactory.cpp
> +		// }
remove

2024-06-19 08:14 UTC, jmillan commented on test/src/mediasoupclient.test.cpp
> +
remove

2024-06-19 08:22 UTC, jmillan approved these changes
Merging into versatica:m120. Comments will be addressed there.

2024-06-19 08:23 UTC, merged